### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by arkinn47**
Implementation of save function.

### CODE REVIEW

**Comment by jakobjpeters** [comment]
The saved data needs to be loaded back later. Do you have a plan on how to accomplish this with your implementation? We had previously decided to use `pickle` for this.

**Comment by sam-baird** [comment]
For saving, we can probably just do a `pickle.dump(self.world, file)` to save the state. There were some issues with the Enums that were causing `pickle` to fail, but I am working on refactoring them now

**Comment by sam-baird** [comment]
What was your reason for removing World.move_organism()? This is causing a unit test to fail

**Comment by sam-baird** [comment]
Its probably better to have a `mutate()` method within the `Genome` class than a separate `Mutate` class. Also the `Procreate` function seems to be unfinished/nonfunctional. Do you have more recent changes to push?

**Comment by jakobjpeters** [comment]
Hi, I see that you're trying to get your branch up to date with the main branch. Committing those changes yourself is error prone, obscures the git history, and makes it appear as if you wrote the code (via git blame). I think it would be best to work on a fresh branch. Also, it would be helpful to use more descriptive names for your commits so that it is easier to identify what those commits are for.

**Pull request closed without merging**
